# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpanderapp', '0003_auto_20160815_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 7, 8, 7, 331349)),
        ),
    ]
