# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 07:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpanderapp', '0004_auto_20160815_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='recent',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 15, 7, 11, 37, 72827, tzinfo=utc)),
        ),
    ]
