# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpanderapp', '0007_auto_20160815_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='recent',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
