# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 07:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpanderapp', '0008_auto_20160815_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='recent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
